name: Build and deploy Node.js app to Azure Web App - Studentregistrationapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies and build frontend
        run: |
          cd Frontend
          npm install
          npm run build

      - name: Upload frontend artifact
        uses: actions/upload-artifact@v3
        with:
          name: frontend
          path: Frontend/dist

      - name: Install dependencies for backend
        run: |
          cd Backend
          npm install

      - name: Upload backend artifact
        uses: actions/upload-artifact@v2
        with:
          name: backend
          path: Backend

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download frontend artifact
        uses: actions/download-artifact@v2
        with:
          name: frontend

      - name: Download backend artifact
        uses: actions/download-artifact@v2
        with:
          name: backend

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C5E7F9F59A484EECACCA91E87846A001 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_BC1D02E75DC441159F2DE40B37C0B096 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_6BE4061D2665459F9F617DA652ADC299 }}

      - name: Deploy frontend to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'Studentregistrationapp'
          package: ${{ github.workspace }}/frontend

      - name: Deploy backend to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'Studentregistrationapp'
          package: ${{ github.workspace }}/backend
